### ISSUE TITLE
The links are invalid!

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_gaze-interface#2]
This tutorial will guide you to the use of [Gaze Interface](http://www.icub.org/doc/icub-main/dox/html/icub_gaze_interface.html) component that enables the control of the iCub gaze.

For the above, when I double click the links (http://www.icub.org/doc/icub-main/dox/html/icub_gaze_interface.html) connected to Gaze interface, it is invalid as shown hereinafter.
 
The requested URL /doc/icub-main/dox/html/icub_gaze_interface.html was not found on this server.

Also, for the School materials, some links are invalid and without detailed tutorials, it becomes
harder for beginners.

**Comment by pattacini** [comment]
Thanks for reporting @YANGGANG1971 👍 
It may happen that updated versions of doxygen yield different links to our documentation.
