### ISSUE TITLE
Tutorial fails to start

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_gaze-interface#3]
I used the Gitpod you recommended. 
I cannot launch the tutorial_gaze-interface-detector as follows.

![image](https://user-images.githubusercontent.com/55526431/69511079-73221500-0f82-11ea-85c1-ce3ac91d6619.png)

**Comment by pattacini** [comment]
Just tested now on Gitpod and it works out of the box.

Try out on a brand new workspace, thus click on https://gitpod.io/#https://github.com/vvv-school/tutorial_gaze-interface.

I've sometimes observed that `iCub_SIM` may struggle to start up from within `yarpmanager`; if it happens, remember to launch `iCub_SIM` from a console instead.
