### ISSUE TITLE
iCub simulator cannot close sometimes!!!

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_gaze-interface#4]
![image](https://user-images.githubusercontent.com/55526431/69840781-171c0100-12a0-11ea-9a45-bb1c89e6e2f1.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

Unfortunately, this is a known issue 🐛 

As we've been migrating to the use of a different simulator (see for example https://github.com/robotology/QA/issues/366), we're not investing resources on fixing this.

Thus, when the simulator hangs, simply kill the process:
```sh
$ killall -9 iCub_SIM
```
