### ISSUE TITLE
Cannot open three executable files? 

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_gaze-interface#5]
Sorry, this is an issue about this tutorial. But I am still not sure whether I should post this issue here.
Download codes from https://github.com/vvv-school/tutorial_gaze-interface. 

Using Gitpod below you suggest run the codes, 
https://6080-a35c8406-fc54-4ef5-91ac-c55de4116e04.ws-ap01.gitpod.io/vnc.html 

 We find below 
![Screenshot from 2020-01-15 16-47-42](https://user-images.githubusercontent.com/55526431/72415344-9cf3fd00-37b7-11ea-973f-68fe72486178.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

This is the right place for opening this issue as it pertains to this tutorial.

Just tried out the tutorial using a brand new Gitpod workspace and it works out of the box.
You could test it yourself by relying on this snapshot (click on the badge):

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/bec4eb77-c2b1-4dc9-8d26-15794dae8394)

However, I've been experiencing some trouble when launching `iCub_SIM` straight from within the `yarpmanager`, thus my suggestion is to start it up from a console.

**Comment by YANGGANG1971** [comment]
Great! All applications can be run now.
But, while running two applications (app and system), I only see a ball that moves around the robot. 
I cannot see the movement of the robot's head.

**Comment by pattacini** [comment]
@YANGGANG1971 by any chance, did you miss to press the connect button within the `yarpmanager` for the `App` application? After having launched all the modules, their opened ports need to be connected in order to exchange information.

**Comment by YANGGANG1971** [comment]
After launched all the modules, I connected all ports.  I can see the images from yarpview.

**Comment by YANGGANG1971** [comment]
More strange is that while running these codes on Ubuntu 16.04, I even cannot see the red ball. 
My yarp version is 3.2.1.
![Screenshot from 2020-01-16 16-35-06](https://user-images.githubusercontent.com/55526431/72506199-c9297f80-3884-11ea-8484-e9dd95ba9977.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

You can find below an animation showing how to run the tutorial from within the snapshot I've provided you with:

| Click to enlarge |
| :---: |
| ![animation][1] |

Hope this helps.

[1]: https://user-images.githubusercontent.com/3738070/72525616-da629400-3864-11ea-8515-6a9255207798.gif
